<a href="https://colab.research.google.com/github/radsrei/Atividade---An-lise-Multidimensional-de-Dados/blob/main/Trabalho_em_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sqlite3

# Conectar ao banco de dados (ou criar um novo se não existir)
conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

# DDL para criar as tabelas
cursor.execute('''
CREATE TABLE Estudante (
    estudanteID INTEGER PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    curso VARCHAR(100) NOT NULL
);
''')

cursor.execute('''
CREATE TABLE Instrutor (
    instrutorID INTEGER PRIMARY KEY,
    curso VARCHAR(100) NOT NULL
);
''')

cursor.execute('''
CREATE TABLE Aula (
    aulaID INTEGER PRIMARY KEY,
    Instituicao VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    estado CHAR(2) NOT NULL
);
''')

cursor.execute('''
CREATE TABLE Aulas_assistidas (
    estudanteID INTEGER,
    instrutorID INTEGER,
    aulaID INTEGER,
    notas DECIMAL(5,2),
    FOREIGN KEY (estudanteID) REFERENCES Estudante(estudanteID),
    FOREIGN KEY (instrutorID) REFERENCES Instrutor(instrutorID),
    FOREIGN KEY (aulaID) REFERENCES Aula(aulaID)
);
''')

# Commitar as mudanças e fechar a conexão
conn.commit()
conn.close()

print("Tabelas criadas com sucesso no 'meu_banco_de_dados.db'!")

OperationalError: table Estudante already exists

In [4]:
import sqlite3

# Conectar ao banco de dados existente
conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

# Inserir dados na tabela Estudante
cursor.execute("""
INSERT INTO Estudante (estudanteID, nome, curso) VALUES
(1, 'Ana Silva', 'Sistemas de Informação'),
(2, 'Bruno Costa', 'Ciência da Computação'),
(3, 'Carla Souza', 'Engenharia de Software'),
(4, 'Diego Lima', 'Sistemas de Informação'),
(5, 'Elena Rosa', 'Ciência da Computação'),
(6, 'Fabio Neto', 'Engenharia de Software'),
(7, 'Gisele Dias', 'Matemática'),
(8, 'Heitor Vaz', 'Física'),
(9, 'Igor Paiva', 'Sistemas de Informação'),
(10, 'Julia Luz', 'Ciência da Computação');
""")

# Inserir dados na tabela Instrutor
cursor.execute("""
INSERT INTO Instrutor (instrutorID, curso) VALUES
(1, 'Sistemas de Informação'),
(2, 'Ciência da Computação'),
(3, 'Engenharia de Software'),
(4, 'Matemática'),
(5, 'Física');
""")

# Inserir dados na tabela Aula
cursor.execute("""
INSERT INTO Aula (aulaID, Instituicao, cidade, estado) VALUES
(1, 'Udesc', 'Joinville', 'SC'),
(2, 'UFSC', 'Florianópolis', 'SC'),
(3, 'USP', 'São Paulo', 'SP'),
(4, 'UFRJ', 'Rio de Janeiro', 'RJ'),
(5, 'Univille', 'Joinville', 'SC');
""")

# Inserir dados na tabela Aulas_assistidas
cursor.execute("""
INSERT INTO Aulas_assistidas (estudanteID, instrutorID, aulaID, notas) VALUES
(1, 2, 1, 70), (2, 1, 2, 85), (3, 3, 5, 45), (4, 4, 1, 90), (5, 5, 3, 66),
(6, 1, 4, 72), (7, 2, 2, 88), (8, 3, 1, 55), (9, 4, 5, 92), (10, 5, 3, 78),
(1, 1, 5, 60), (2, 3, 1, 95), (3, 2, 2, 30), (4, 5, 4, 82), (5, 4, 1, 67),
(6, 3, 3, 74), (7, 1, 1, 89), (8, 5, 2, 40), (9, 2, 4, 91), (10, 4, 5, 55),
(1, 3, 2, 77), (2, 5, 4, 84), (3, 1, 1, 62), (4, 2, 3, 98), (5, 3, 5, 50),
(6, 5, 1, 81), (7, 4, 2, 73), (8, 1, 4, 44), (9, 3, 3, 94), (10, 2, 1, 68),
(1, 5, 3, 59), (2, 4, 5, 87), (3, 3, 1, 35), (4, 1, 2, 79), (5, 2, 4, 63),
(6, 4, 1, 88), (7, 5, 3, 71), (8, 2, 5, 49), (9, 1, 2, 96), (10, 3, 4, 52),
(1, 4, 1, 65), (2, 2, 2, 83), (3, 5, 3, 25), (4, 3, 5, 99), (5, 1, 1, 70),
(6, 2, 4, 86), (7, 3, 2, 74), (8, 4, 1, 41), (9, 5, 3, 93), (10, 1, 5, 58),
(1, 2, 5, 69), (2, 1, 1, 80), (3, 4, 2, 38), (4, 5, 3, 97), (5, 3, 4, 61),
(6, 1, 1, 85), (7, 2, 5, 76), (8, 3, 4, 47), (9, 4, 2, 90), (10, 5, 1, 54),
(1, 3, 3, 72), (2, 5, 1, 82), (3, 1, 4, 33), (4, 2, 5, 95), (5, 4, 2, 64),
(6, 3, 1, 89), (7, 5, 4, 70), (8, 1, 3, 42), (9, 2, 1, 91), (10, 4, 2, 56),
(1, 5, 2, 66), (2, 4, 4, 88), (3, 3, 5, 29), (4, 1, 1, 94), (5, 2, 3, 68),
(6, 4, 2, 87), (7, 3, 1, 75), (8, 5, 5, 46), (9, 1, 4, 92), (10, 2, 3, 51),
(1, 4, 5, 63), (2, 3, 2, 81), (3, 2, 4, 31), (4, 5, 1, 96), (5, 1, 2, 69),
(6, 5, 3, 84), (7, 4, 1, 72), (8, 2, 2, 43), (9, 3, 5, 90), (10, 1, 4, 57),
(1, 2, 1, 71), (2, 1, 3, 86), (3, 4, 5, 34), (4, 3, 2, 98), (5, 5, 1, 65),
(6, 1, 2, 83), (7, 2, 4, 78), (8, 3, 3, 48), (9, 4, 1, 95), (10, 5, 2, 53);
""")

# Commitar as mudanças e fechar a conexão
conn.commit()
conn.close()

print("Dados inseridos com sucesso no 'meu_banco_de_dados.db'!")

Dados inseridos com sucesso no 'meu_banco_de_dados.db'!

### Consulta A: Estudantes com notas acima de 65 em aulas em SC, onde o curso do instrutor é diferente do curso do estudante.

In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

query_a = """
SELECT e.nome, a.Instituicao, f.notas
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
JOIN Instrutor i ON f.instrutorID = i.instrutorID
JOIN Aula a ON f.aulaID = a.aulaID
WHERE a.estado = 'SC'
  AND i.curso <> e.curso
  AND f.notas > 65;
"""

cursor.execute(query_a)
results_a = cursor.fetchall()

df_a = pd.DataFrame(results_a, columns=['Nome Estudante', 'Instituição Aula', 'Notas'])
display(df_a)

conn.close()

   Nome Estudante Instituição Aula  Notas
0       Ana Silva            Udesc     70
1     Bruno Costa             UFSC     85
2      Diego Lima            Udesc     90
3     Gisele Dias             UFSC     88
4      Igor Paiva         Univille     92
5     Bruno Costa            Udesc     95
6      Elena Rosa            Udesc     67
7     Gisele Dias            Udesc     89
8       Ana Silva             UFSC     77
9      Fabio Neto            Udesc     81
10    Bruno Costa         Univille     87
11     Fabio Neto            Udesc     88
12     Diego Lima         Univille     99
13     Elena Rosa            Udesc     70
14    Gisele Dias             UFSC     74
15      Ana Silva         Univille     69
16    Bruno Costa            Udesc     80
17     Fabio Neto            Udesc     85
18    Gisele Dias         Univille     76
19     Igor Paiva             UFSC     90
20    Bruno Costa            Udesc     82
21     Diego Lima         Univille     95
22     Igor Paiva            Udesc     91
23      Ana Silva             UFSC     66
24     Fabio Neto             UFSC     87
25    Gisele Dias            Udesc     75
26    Bruno Costa             UFSC     81
27     Diego Lima            Udesc     96
28     Elena Rosa             UFSC     69
29     Igor Paiva         Univille     90
30      Ana Silva            Udesc     71
31     Diego Lima             UFSC     98
32     Fabio Neto             UFSC     83
33     Igor Paiva            Udesc     95

### Consulta B: Média de notas por estudante e instrutor em Joinville.

In [7]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

query_b = """
SELECT e.nome AS Aluno, i.instrutorID, AVG(f.notas) AS media_notas
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
JOIN Aula a ON f.aulaID = a.aulaID
JOIN Instrutor i ON f.instrutorID = i.instrutorID
WHERE a.cidade = 'Joinville'
GROUP BY e.nome, i.instrutorID;
"""

cursor.execute(query_b)
results_b = cursor.fetchall()

df_b = pd.DataFrame(results_b, columns=['Aluno', 'ID Instrutor', 'Média Notas'])
display(df_b)

conn.close()

          Aluno  ID Instrutor  Média Notas
0     Ana Silva             1    60.000000
1     Ana Silva             2    70.000000
2     Ana Silva             4    64.000000
3   Bruno Costa             1    80.000000
4   Bruno Costa             3    95.000000
5   Bruno Costa             4    87.000000
6   Bruno Costa             5    82.000000
7   Carla Souza             1    62.000000
8   Carla Souza             3    36.333333
9   Carla Souza             4    34.000000
10   Diego Lima             1    94.000000
11   Diego Lima             2    95.000000
12   Diego Lima             3    99.000000
13   Diego Lima             4    90.000000
14   Diego Lima             5    96.000000
15   Elena Rosa             1    70.000000
16   Elena Rosa             3    50.000000
17   Elena Rosa             4    67.000000
18   Elena Rosa             5    65.000000
19   Fabio Neto             1    85.000000
20   Fabio Neto             3    89.000000
21   Fabio Neto             4    88.000000
22   Fabio Neto             5    81.000000
23  Gisele Dias             1    89.000000
24  Gisele Dias             2    76.000000
25  Gisele Dias             3    75.000000
26  Gisele Dias             4    72.000000
27   Heitor Vaz             2    49.000000
28   Heitor Vaz             3    55.000000
29   Heitor Vaz             4    41.000000
30   Heitor Vaz             5    46.000000
31   Igor Paiva             2    91.000000
32   Igor Paiva             3    90.000000
33   Igor Paiva             4    93.500000
34    Julia Luz             1    58.000000
35    Julia Luz             2    68.000000
36    Julia Luz             4    55.000000
37    Julia Luz             5    54.000000

### Consulta C: Média de notas por instrutor em Joinville.

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

query_c = """
SELECT i.instrutorID, AVG(f.notas) AS media_notas
FROM Aulas_assistidas f
JOIN Instrutor i ON f.instrutorID = i.instrutorID
JOIN Aula a ON f.aulaID = a.aulaID
WHERE a.cidade = 'Joinville'
GROUP BY i.instrutorID;
"""

cursor.execute(query_c)
results_c = cursor.fetchall()

df_c = pd.DataFrame(results_c, columns=['ID Instrutor', 'Média Notas'])
display(df_c)

conn.close()

   ID Instrutor  Média Notas
0             1    74.750000
1             2    73.625000
2             3    66.200000
3             4    70.750000
4             5    70.666667

### Consulta D: Média de notas por curso de estudante.

In [9]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

query_d = """
SELECT e.curso, AVG(f.notas) AS media_curso
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
GROUP BY e.curso;
"""

cursor.execute(query_d)
results_d = cursor.fetchall()

df_d = pd.DataFrame(results_d, columns=['Curso Estudante', 'Média Curso'])
display(df_d)

conn.close()

          Curso Estudante  Média Curso
0   Ciência da Computação    69.200000
1  Engenharia de Software    59.550000
2                  Física    45.500000
3              Matemática    76.600000
4  Sistemas de Informação    84.133333

### Consulta E: Média de notas por curso de estudante e curso de instrutor.

In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

query_e = """
SELECT e.curso AS curso_estudante, i.curso AS curso_instrutor, AVG(f.notas) AS media
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
JOIN Instrutor i ON f.instrutorID = i.instrutorID
GROUP BY e.curso, i.curso;
"""

cursor.execute(query_e)
results_e = cursor.fetchall()

df_e = pd.DataFrame(results_e, columns=['Curso Estudante', 'Curso Instrutor', 'Média'])
display(df_e)

conn.close()

           Curso Estudante         Curso Instrutor      Média
0    Ciência da Computação   Ciência da Computação  66.600000
1    Ciência da Computação  Engenharia de Software  67.800000
2    Ciência da Computação                  Física  68.857143
3    Ciência da Computação              Matemática  69.500000
4    Ciência da Computação  Sistemas de Informação  72.142857
5   Engenharia de Software   Ciência da Computação  49.000000
6   Engenharia de Software  Engenharia de Software  54.400000
7   Engenharia de Software                  Física  63.333333
8   Engenharia de Software              Matemática  61.750000
9   Engenharia de Software  Sistemas de Informação  67.000000
10                  Física   Ciência da Computação  46.000000
11                  Física  Engenharia de Software  50.000000
12                  Física                  Física  43.000000
13                  Física              Matemática  41.000000
14                  Física  Sistemas de Informação  43.000000
15              Matemática   Ciência da Computação  80.666667
16              Matemática  Engenharia de Software  74.500000
17              Matemática                  Física  70.500000
18              Matemática              Matemática  72.500000
19              Matemática  Sistemas de Informação  89.000000
20  Sistemas de Informação   Ciência da Computação  83.571429
21  Sistemas de Informação  Engenharia de Software  88.333333
22  Sistemas de Informação                  Física  82.166667
23  Sistemas de Informação              Matemática  82.500000
24  Sistemas de Informação  Sistemas de Informação  84.200000

### Consulta F: Média de notas por estado, cidade e instituição com ROLLUP.

In [13]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

# SQLite não suporta diretamente WITH ROLLUP como a sintaxe mostrada.
# Uma alternativa é usar UNION ALL para simular o ROLLUP ou agrupar em diferentes níveis.
# Para fins de demonstração, vou simular o ROLLUP em SQLite com UNION ALL.

# A consulta original com WITH ROLLUP que causou o erro.
# query_f_sqlite = """
# SELECT
#     a.estado,
#     a.cidade,
#     a.Instituicao,
#     AVG(f.notas) AS media_notas
# FROM Aulas_assistidas f
# JOIN Aula a ON f.aulaID = a.aulaID
# GROUP BY a.estado, a.cidade, a.Instituicao WITH ROLLUP;
# """

# Vamos usar a sintaxe alternativa para simular o ROLLUP com UNION ALL no SQLite.
query_f_fixed = """
SELECT
    a.estado,
    a.cidade,
    a.Instituicao,
    AVG(f.notas) AS media_notas
FROM Aulas_assistidas f
JOIN Aula a ON f.aulaID = a.aulaID
GROUP BY a.estado, a.cidade, a.Instituicao

UNION ALL

SELECT
    a.estado,
    a.cidade,
    NULL AS Instituicao, -- Subtotal por cidade e estado
    AVG(f.notas) AS media_notas
FROM Aulas_assistidas f
JOIN Aula a ON f.aulaID = a.aulaID
GROUP BY a.estado, a.cidade

UNION ALL

SELECT
    a.estado,
    NULL AS cidade, -- Subtotal por estado
    NULL AS Instituicao,
    AVG(f.notas) AS media_notas
FROM Aulas_assistidas f
JOIN Aula a ON f.aulaID = a.aulaID
GROUP BY a.estado

UNION ALL

SELECT
    NULL AS estado, -- Total geral
    NULL AS cidade,
    NULL AS Instituicao,
    AVG(f.notas) AS media_notas
FROM Aulas_assistidas f
JOIN Aula a ON f.aulaID = a.aulaID
ORDER BY estado DESC, cidade DESC, Instituicao DESC; -- Ordena para ter os totais no final ou onde fizer mais sentido
"""

cursor.execute(query_f_fixed)
results_f = cursor.fetchall()

df_f = pd.DataFrame(results_f, columns=['Estado', 'Cidade', 'Instituição', 'Média Notas'])
display(df_f)

conn.close()

   Estado          Cidade Instituição  Média Notas
0      SP       São Paulo         USP    70.941176
1      SP       São Paulo        None    70.941176
2      SP            None        None    70.941176
3      SC       Joinville    Univille    64.529412
4      SC       Joinville       Udesc    75.000000
5      SC       Joinville        None    70.954545
6      SC   Florianópolis        UFSC    70.590909
7      SC   Florianópolis        None    70.590909
8      SC            None        None    70.833333
9      RJ  Rio de Janeiro        UFRJ    66.529412
10     RJ  Rio de Janeiro        None    66.529412
11     RJ            None        None    66.529412
12   None            None        None    70.120000

### Consulta G: Média de notas por curso de estudante e curso de instrutor com ROLLUP, combinado com UNION.

In [14]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('meu_banco_de_dados.db')
cursor = conn.cursor()

# SQLite não suporta diretamente WITH ROLLUP. Precisamos simular com UNION ALL.
query_g_fixed = """
-- Agregação por curso de estudante e curso de instrutor
SELECT
    e.curso AS curso_estudante,
    i.curso AS curso_instrutor,
    AVG(f.notas) AS media
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
JOIN Instrutor i ON f.instrutorID = i.instrutorID
GROUP BY e.curso, i.curso

UNION ALL

-- Subtotal por curso de estudante (instrutor é NULL)
SELECT
    e.curso AS curso_estudante,
    NULL AS curso_instrutor,
    AVG(f.notas) AS media
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
JOIN Instrutor i ON f.instrutorID = i.instrutorID
GROUP BY e.curso

UNION ALL

-- Subtotal por curso de instrutor (estudante é NULL)
SELECT
    NULL AS curso_estudante,
    i.curso AS curso_instrutor,
    AVG(f.notas) AS media
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
JOIN Instrutor i ON f.instrutorID = i.instrutorID
GROUP BY i.curso

UNION ALL

-- Total geral (ambos NULL)
SELECT
    NULL AS curso_estudante,
    NULL AS curso_instrutor,
    AVG(f.notas) AS media
FROM Aulas_assistidas f
JOIN Estudante e ON f.estudanteID = e.estudanteID
JOIN Instrutor i ON f.instrutorID = i.instrutorID
ORDER BY curso_estudante ASC, curso_instrutor ASC;
"""

cursor.execute(query_g_fixed)
results_g = cursor.fetchall()

df_g = pd.DataFrame(results_g, columns=['Curso Estudante', 'Curso Instrutor', 'Média'])
display(df_g)

conn.close()

           Curso Estudante         Curso Instrutor      Média
0                     None                    None  70.120000
1                     None   Ciência da Computação  69.950000
2                     None  Engenharia de Software  68.571429
3                     None                  Física  69.600000
4                     None              Matemática  70.789474
5                     None  Sistemas de Informação  71.800000
6    Ciência da Computação                    None  69.200000
7    Ciência da Computação   Ciência da Computação  66.600000
8    Ciência da Computação  Engenharia de Software  67.800000
9    Ciência da Computação                  Física  68.857143
10   Ciência da Computação              Matemática  69.500000
11   Ciência da Computação  Sistemas de Informação  72.142857
12  Engenharia de Software                    None  59.550000
13  Engenharia de Software   Ciência da Computação  49.000000
14  Engenharia de Software  Engenharia de Software  54.400000
15  Engenharia de Software                  Física  63.333333
16  Engenharia de Software              Matemática  61.750000
17  Engenharia de Software  Sistemas de Informação  67.000000
18                  Física                    None  45.500000
19                  Física   Ciência da Computação  46.000000
20                  Física  Engenharia de Software  50.000000
21                  Física                  Física  43.000000
22                  Física              Matemática  41.000000
23                  Física  Sistemas de Informação  43.000000
24              Matemática                    None  76.600000
25              Matemática   Ciência da Computação  80.666667
26              Matemática  Engenharia de Software  74.500000
27              Matemática                  Física  70.500000
28              Matemática              Matemática  72.500000
29              Matemática  Sistemas de Informação  89.000000
30  Sistemas de Informação                    None  84.133333
31  Sistemas de Informação   Ciência da Computação  83.571429
32  Sistemas de Informação  Engenharia de Software  88.333333
33  Sistemas de Informação                  Física  82.166667
34  Sistemas de Informação              Matemática  82.500000
35  Sistemas de Informação  Sistemas de Informação  84.200000